//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PgDataToSql
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JzDBEntities : DbContext
    {
        public JzDBEntities()
            : base("name=JzDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public DbSet<Class> Class { get; set; }
        public DbSet<ClassInfo> ClassInfo { get; set; }
        public DbSet<ClassInfoContent> ClassInfoContent { get; set; }
        public DbSet<ClassWeek> ClassWeek { get; set; }
        public DbSet<ClassWeekType> ClassWeekType { get; set; }
        public DbSet<Client> Client { get; set; }
        public DbSet<University> University { get; set; }
        public DbSet<User> User { get; set; }
    }
}
