//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PgDataToSql
{
    using System;
    using System.Collections.Generic;
    
    public partial class University
    {
        public string CreateBy { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int Id { get; set; }
        public string Name { get; set; }
        public string Intro { get; set; }
        public string Image { get; set; }
    }
}
